Repository VAR-solutions/Algorithms, pull requests merged in 2020-10, with the labels that each got.

#1322 Other algorithms/Number to words/C++/num_to_words.cpp
  Other Algorithms/num_to_words.cpp
Labels: good-work

#1422 Added bucket_sort.c and Modified Readme.md
  Sorting/Bucket Sort/C/bucket_sort.c
  Sorting/README.md
Labels: good-work

#1330 Added mergeSort, combSort, pancakeSort in Golang
  Searching/binary search/go/binarySearch.go
  Sorting/Comb Sort/Go/combSort.go
  Sorting/Merge Sort/Go/mergeSort.go
  Sorting/Pancake Sorting/Go/pancakeSort.go
Labels: hacktoberfest-accepted

#1131 Reverse doubly linked list in C++
  LinkedList/Reverse-DoublyLinkedList/CPP/ReverseDoublyLinkedList.cpp
Labels: hacktoberfest-accepted

#1310 Added kadane's_algorithm By zahinekbal
  data structures/array/Maximum-Subarray-Sum/KADANE'S_ALGORITHM/C++/Kadane's_algorithm.c++
Labels: hacktoberfest-accepted

#1347 Find nth term in fibonacci series using recursion
  Mathematics/fibonacci/cpp/fibonacciUsingRecursion.cpp
Labels: hacktoberfest-accepted

#1307 Create NumberToWords.py
  Other Algorithms/NumberToWords.py
Labels: hacktoberfest-accepted

#1138 Create factorial_withmod.cpp
  Mathematics/factorial/cpp/factorial_withmod.cpp
Labels: duplicate

#1368 Added code for vertical order traversal of a tree | C++
  Tree/Traverals/CPP/vertical order traversal.cpp
Labels: needs-work

#1217 Kahn's Algorithm Added
  Graphs/Kahn Algorithm/cpp/kahn-algorithm.cpp
Labels: hacktoberfest-accepted

#1574 Create cppgnome.cpp
  Sorting/Gnome Sort/cppgnome.cpp
Labels: hacktoberfest-accepted

#1573 Create gnome.java
  Sorting/Gnome Sort/gnome.java
Labels: hacktoberfest-accepted

#1572 Create cscocktail.cs
  Sorting/Cocktail/cscocktail.cs
Labels: hacktoberfest-accepted

#1571 Create cocktail.java
  Sorting/Cocktail/cocktail.java
Labels: hacktoberfest-accepted

#1308 Solved #163 added : partition list leet code
  LinkedList/LinkedListPartition/python/partition-leet-code.c
  LinkedList/LinkedListPartition/python/readme.md
Labels: hacktoberfest-accepted

#1148 Create PHP
  Sorting/Heapsort/php/heap_sort.php
Labels: hacktoberfest-accepted, needs-work

#1153 Create PHP
  Sorting/Pancake Sorting/php/pancake_sort.php
Labels: follow-directory-structure, hacktoberfest-accepted, needs-work

#1151 Create C++
  Sorting/Pancake Sorting/CPP/pancake_sort.cpp
Labels: follow-directory-structure, hacktoberfest-accepted, needs-work

#1150 Create PHP
  Sorting/Selection Sort/php/selection_sort.php
Labels: follow-directory-structure, hacktoberfest-accepted, needs-work

#1149 Create C#
  Sorting/Radix Sort/C#/radix_sort.cs
Labels: hacktoberfest-accepted, needs-work
